### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by wookiesh** [pascalw/Airplayer#1]
Hi, first wonderfull :)
Wanted to give it a try, but as ever, someone has done it faster and better !

Just a thing, with the version from today 12:41 and xbmc 2:10.00~svn34731-lucid1 i cannot play pictures (black screen) and the video always starts from the beginning and i cannot navigate, is it normal ?

Thanks !

**Comment by pascalw** [comment]
Hi,

it's true seeking doesn't work yet, i didn't implemented it yet.

Pictures should be working though, on OSX and Ubuntu 9.10 it's working for me.

So far it has been just a quick hack, in the next few days (or probably after christmas) I'll be working on the currently missing features and I'll also be making the code a bit more robust with decent error handling and logging so we can better track down errors.

**Comment by wookiesh** [comment]
I just tried on Osx, for youtube movies it's ok, but photos do not appear. I'll chek a bit deeper what happens this weekend. Thanks again!!!

**Comment by pascalw** [comment]
I've just pushed some changes to the repo, could you please check if pictures work for you now?
