### ISSUE TITLE
Orientation of Videos incorrect

### ISSUE THREAD

**Issue by stevewastaken** [pascalw/Airplayer#10]
I have just updated to the iOS4.3 version but when I playback videos in the 'Photos' app they work but in some circumstances are displayed in the wrong orientation.
- Videos that have been recorded using iphone camera are displayed (incorrectly) in landscape. They display correctly on the iphone
- I also have videos in the Photos app that have been edited with iMovie and these display correctly i.e. portrait
- Photos and everything else seems to work fine

I am using this with Ubuntu and XBMC

Thanks for your help!

**Comment by esetnik** [comment]
I have  similar issue using Plex.  Photos and videos pushed from my iPhone 4 running iOS 4.3 begin to play in the correct orientation, but they skip horribly for 3 seconds and then plex stops playback.

**Comment by pascalw** [comment]
Well it's up to the media player to handle movie and picture orientation. Orientation information is usually contained in the file headers and the media player has to read this information and act accordingly.

@esetnik Can you elaborate on that?

**Comment by stevewastaken** [comment]
I have been doing more research on this and it seems the iPhone uses effectively a non standard rotation flag to indicate orientation of video. From what I have read only QuickTime actually looks for this flag and therefore nearly all over players have this issue when using iPhone video.

If this is true then everyone should be seeing this problem...

**Comment by esetnik** [comment]
In response to my previous post.  I am on a wireless-n network running iOS 4.3 on an iPhone 4.  Playing youtube video thru airplay on Plex on my mac mini works wonderfully.  What doesn't work is when I try to play a video from my photos on my iPhone.  The video begins to play, I get 3-10 choppy frames and 1-2s worth of audio, then Plex returns to the main screen and the device still says AirPlay "This movie is now playing on ..."

**Comment by pascalw** [comment]
I'm closing this since this is out of control for Airplayer, so not relevant.
