### ISSUE TITLE
3rd Party Apps Not Working

### ISSUE THREAD

**Issue by esetnik** [pascalw/Airplayer#11]
Firstly i'd like to say how great this project is.  Airplay support to mac devices is something that apple should have included from the beginning.

Since they didn't I'm glad someone has taken the initiative.

Airplayer works great for apple's built in apps such as youtube, but I am having trouble streaming video from 60 minutes app.  I think this may have to do with the streaming video format utilized by some third party apps.  I believe it is .m3u8?  Basically the problem is that on the device when I click airplay, the machine running Airplayer doesn't show up in the list of choices.

**Comment by pascalw** [comment]
A lot of 3rd party apps indeed use m3u8 files for streaming playback. Unfortunately this format is not supported (yet) by XBMC/Plex/Boxee, so apps using this format will not work with Airplayer for XBMC.

If Airplayer doesn't show up in the Airplay devices list that probably means that IOS 4.3 final uses slightly different Bonjour records then IOS 4.3 betas did. I don't have an Apple TV 2 myself, so I cannot verify this.

If someone with an ATV2 can check what records the ATV publishes on IOS 4.3, please let me now so I can incorporate the changes into Airplayer.

Btw I must say that for me third party apps do recognize Airplayer. Are you running the latest version with IOS 4.3 support?

**Comment by esetnik** [comment]
I also noticed that airplayer doesn't work for drm content.  Is that also a factor when playing 3rd party video?  Is that the same reason that audio from apps like pandora is unstreamable?  I must admit i've not got much experience in python but would like to help you with any debug logs etc that you might need.

**Comment by pascalw** [comment]
That's right, you'll find that in the README too ;)
