### ISSUE TITLE
Not reaaly starting?

### ISSUE THREAD

**Issue by michielveenstra** [pascalw/Airplayer#14]
After some struggling with the scripts I believe I managed to turn this thing on... But then again not. When I run the Python script it says Airvideo is starting and on screen it says the same. However, when I select a video on my iPad and use AirPlay to transfer it to XBMC, the screen says it does so but the video won't play, it kinda just freezes and nothing shows up in my tv. I can not play the video properly until I switch AirPlay back to the iPad. 

Is this a known problem?

**Comment by pascalw** [comment]
What are you trying to play? If XBMC does not support the media you are sending, it won't play. If you set Debug = True in settings.py, do you see any related errors?

**Comment by michielveenstra** [comment]
I'll try that tomorrow, thanks for the reply. I tried playing both a Youtube
movie as one on my iPod app.

2011/3/29 PascalW <
reply@reply.github.com>

> What are you trying to play? If XBMC does not support the media you are
> sending, it won't play. If you set Debug = True in settings.py, do you see
> any related errors?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PascalW/Airplayer/issues/14#comment_932142

## 

Michiel Veenstra

**Comment by pascalw** [comment]
YouTube should be no problem. iPod may be a problem if your content is DRM protected (from iTunes for example).

**Comment by michielveenstra** [comment]
I tried Youtube and a homevideo, but still nothing. Debug gave me this:
2011-03-30 08:42:29 [INFO] Starting Airplayer
2011-03-30 08:42:29 [DEBUG] TEMP DIR: /tmp/tmp8V5O12
2011-03-30 08:42:29 [DEBUG] Sending wake event
2011-03-30 08:42:30 [DEBUG] Registered bonjour service  
XBMCLive._airplay._tcp.

Op schreef PascalW  
reply@reply.github.com:

**Comment by pascalw** [comment]
By the looks of your logging information, Airplaying is not receiving any requests from your iPad. Could it be a firewall is blocking the connection? Airplayer uses port 6002.

**Comment by michielveenstra** [comment]
As far as I can tell, taken care of as well

2011/3/30 PascalW <
reply@reply.github.com>

> By the looks of your logging information, Airplaying is not receiving any
> requests from your iPad. Could it be a firewall is blocking the connection?
> Airplayer uses port 6002.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PascalW/Airplayer/issues/14#comment_937016

## 

Michiel Veenstra

**Comment by pascalw** [comment]
Well there's not much I can do then, sorry. Should be a connection issue.

**Comment by michielveenstra** [comment]
Tnx anyway Pascal, for your time & effort.

2011/3/30 PascalW <
reply@reply.github.com>

> Well there's not much I can do then, sorry. Should be a connection issue.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PascalW/Airplayer/issues/14#comment_937693

## 

Michiel Veenstra
