### ISSUE TITLE
does not seem to work with iphone youtube.app

### ISSUE THREAD

**Issue by jingoman** [pascalw/Airplayer#15]
was fully working yesterday. only aspect changed was an update to the iphone's remote.app, now there are no airplay icons when playing youtube videos on the iphone.

content from iphone's photos seems to work, so does playing video's directly from my iMac's itunes when playing videos.

**Comment by pascalw** [comment]
I'm not able to reproduce this. Are you sure nothing else changed? Did you try rebooting the iPhone?

**Comment by jingoman** [comment]
yes, although i cannot label what went wrong here, following an iPhone reboot, i was once again able to see & use the airplay icon when playing video in the device's youtube.app.

at this point, i am happy to consider this issue resolved. many thanks for the suggestion.

**Comment by pascalw** [comment]
I've experienced it before and I neither have a clue what happened. Seemed like the airplay daemon on the iPhone somehow crashed or something.
