### ISSUE TITLE
Problem with Justin.TV

### ISSUE THREAD

**Issue by neoflex** [pascalw/Airplayer#18]
Hi,

I tried to use the airplayer functionality with the JustinTV app on my IPhone. It doesn't work, it looks like it is because the video is streamed so there isn't any real "start time". I guess there should be the same problem for any video streamed to the iThing.

<code>2011-07-02 10:31:42 [WARNING] Failed to set start position
WARNING:airplayer:Failed to set start position
</code>

**Comment by pascalw** [comment]
Does JustinTV use m3u8 HTTP streaming? This is not supported by XBMC currently. See [this](https://github.com/PascalW/Airplayer/issues/11) issue.

**Comment by neoflex** [comment]
It seems like they use m3u8 indeed :(

**Comment by pascalw** [comment]
Well the good news is that once XBMC supports m3u8 it will work.
