### ISSUE TITLE
Ubuntu init script will not start if a different python daemon is already running

### ISSUE THREAD

**Issue by tomislav** [pascalw/Airplayer#2]
The Ubuntu init script will not start if a different python daemon is already running

<code>root@revo:/usr/local/bin/airplayer# /etc/init.d/airplayer start
Starting airplayer: /usr/bin/python already running.
airplayer</cody>

The solution is to make airplayer.py executable and change COMMAND in the init script to just

<code>COMMAND="$DAEMON"</code>

**Comment by pascalw** [comment]
Yes that was my initial thought, but I wanted to be able to run airplayer from within virtualenv.
But this way that obviously doesn't work, I'll fix it.

**Comment by pascalw** [comment]
It's fixed. If you want to run airplayer from within a virtualenv you'll just have to wrap it up in a bash script or something. If anyone knows a more decent way to run a python script inside a virtualenv as a daemon please let me know (no changing of the she-bang please).
