### ISSUE TITLE
Downloading requirements failed, can't find tornado

### ISSUE THREAD

**Issue by hoschi** [pascalw/Airplayer#23]
Hi,

I'm under ubunt karmic and the step "pip install -r requirements.txt" fails. If I interprete the output corect (last line) The tornado package has a version conflict with the specified simplejson version?! Is that right? Any suggestions?

Here is the output: http://pastie.org/2497227

thanks for help,
hoschi

**Comment by trevorharwell** [comment]
just download the newest version of simplejson:  http://pypi.python.org/pypi/simplejson/

download it and unpack it.  run 'python setup.py install' (you might need to run that with sudo)
