### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'requirements.txt

### ISSUE THREAD

**Issue by Demorgorgon** [pascalw/Airplayer#29]
Hi all, I am kinda new to all of this so dont hate me for being a noob! 

I was trying to install Airplayer on my Ubuntu system with XBMClive 10.1, on the pip install -r requirements.txt I get the following error:

xbmc@XBMCLive:~$ pip install -r requirements.txt
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 406, in run
    for req in parse_requirements(filename, finder=finder):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3268, in parse_requirements
    filename, content = get_file_content(filename, comes_from=comes_from)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3259, in get_file_content
    f = open(url)
IOError: [Errno 2] No such file or directory: 'requirements.txt'

Storing complete log in ./pip-log.txt

Could someone help me out?

**Comment by pascalw** [comment]
Hi,

it seems that you didn't cd to the airplay source directory yet.

So first execute `cd <airplay source path>`.

Btw, recent versions of XBMC (since 11) include built-in Airplay support. It's probably easier for you to use that.

**Comment by Demorgorgon** [comment]
Hi PacalW,

Thank you very much for your fast reply. However I get another error when using your code, namely:

xbmc@XBMCLive:~$ cd Airplay
xbmc@XBMCLive:~/Airplay$ pip install requirements.txt
Downloading/unpacking requirements.txt
  Could not fetch URL http://pypi.python.org/simple/requirements.txt: HTTP Error 404: Not Found (requirements.txt does not have any releases)
  Will skip URL http://pypi.python.org/simple/requirements.txt when looking for download links for requirements.txt
  Real name of requirement requirements.txt is requirements.txt
  Could not fetch URL http://pypi.python.org/simple/requirements.txt: HTTP Error 404: Not Found (requirements.txt does not have any releases)
  Will skip URL http://pypi.python.org/simple/requirements.txt when looking for download links for requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
No distributions at all found for requirements.txt
Storing complete log in ./pip-log.txt

Do you happen to also know what this means ?

I would really like to use Eden, however the GUI is unusually laggy and slow. Furthermore I dont have the knowledge required for fixing this, neither do I want to wreck my working XBMC-system. But thanks for the tip :)

**Comment by pascalw** [comment]
It seems like you're missing the `-r` parameter on the `pip install` command.

Make sure you are executing `pip install -r requirements.txt`.

**Comment by Demorgorgon** [comment]
That worked like a charm! Thanks PascalW
