### ISSUE TITLE
Mac OSX Launchd Script

### ISSUE THREAD

**Issue by jayshed** [pascalw/Airplayer#4]
The Python script works great, but I am having trouble getting the launchd script to start the service.  I am using OSX 10.6.6 and Python 2.7.1.  Is there anything I may be missing?

Thanks!

**Comment by pascalw** [comment]
Can you describe what's not working please?

Did you edit the org.pwiddershoven.airplay.plist file as described in the installation instructions?

**Comment by jayshed** [comment]
I have edited the file as described in the instructions including providing read, write and execute rights on airplayer.py.  The service loads as I have checked with launchctl.  I have tried moving the files into different directories. When I run airplayer.py manually it works perfectly.

**Comment by pascalw** [comment]
Hm I'm really not sure why it isn't working for you. Is there a logfile created in /Users/YourUsername/Library/Logs/airplayer.log? If it is, could you post it's contents please?

**Comment by jayshed** [comment]
No log file.

**Comment by pascalw** [comment]
That means that Airplayer is not (correctly) started. I can't really tell what's wrong, but I tend to think you did something wrong in your configuration.

**Comment by pascalw** [comment]
Hm I see I forgot to include one needed command.

You should execute the following command to enable the launchd script:

```
 launchctl load -w /Users/YOUR_USERNAME_/Library/LaunchAgents/org.pwiddershoven.airplayer.plist
```

After that you should be able to start Airplayer by executing `launchctl start|stop org.pwiddershoven.airplayer`.

I've updated the installation instructions accordingly. 

Could you let me know if that works for you please?

**Comment by jayshed** [comment]
Still not working.  I think it has to do with executing airplayer.py.  Is there a way of testing whether it is executable from the terminal window?

**Comment by pascalw** [comment]
Yes.

In the terminal, enter the path to airplayer.py (without python in front of it, so just path/to/airplayer.py) and hit enter. If you get "permission denied", it's not executable.

Either way, you should just make it executable by issuing `chmod +x path/to/airplayer.py`.

**Comment by pascalw** [comment]
I've updated the [installation insturctions](https://github.com/PascalW/Airplayer/blob/master/INSTALL.mdown) for running Airplayer with launchd on Mac OS X. It now includes instructions to make sure the org.pwiddershoven.airplay.plist file has the right file permissions. That'll fix your problem.
