### ISSUE TITLE
AirPlay in iOS 4.3 doesn't work from MobileSafari and others

### ISSUE THREAD

**Issue by 343max** [pascalw/Airplayer#7]

**Comment by pascalw** [comment]
How did you test it? Airplay is disabled by default. Website publishers and app developers should explicitly allow airplay video streaming.

I've created a test webpage [here](http://pwiddershoven.nl/files/airplay/index.html) with an embedded html5 movie. You should be able to play that through Airplay, in my tests it works.

**Comment by 343max** [comment]
Your sample works perfectly, thank you.

Each and every website developer has to allow AirPlay? And I hoped, AirPlay could become usefull after all

**Comment by pascalw** [comment]
Yes, for now at least. Maybe when IOS 4.3 is officially released it will be enabled by default, but I don't think so.
